Repository Software-Engineering-1-Group-13/Bookstore-API, pull requests merged in 2023-10, with the labels that each got.

#43 bsapi-9-create-book-given-details
  src/main/java/com/bookstore/bookstoreapi/data/configuration/DataInitializer.java
  src/main/java/com/bookstore/bookstoreapi/data/entity/Book.java
Labels: 8 hours

#40 BSAPI-24: Leaving comment on a book
  src/main/java/com/bookstore/bookstoreapi/data/configuration/DataInitializer.java
  src/main/java/com/bookstore/bookstoreapi/data/controller/RatingController.java
  src/main/java/com/bookstore/bookstoreapi/data/entity/Book.java
  src/main/java/com/bookstore/bookstoreapi/data/entity/Comment.java
  src/main/java/com/bookstore/bookstoreapi/data/entity/Customer.java
  src/main/java/com/bookstore/bookstoreapi/data/repository/CommentRepository.java
  src/main/java/com/bookstore/bookstoreapi/data/service/RatingService.java
Labels: 2 hours, Feature

#44 BSAPI-9: Given details create book
  settings.gradle.kts
  src/main/java/com/bookstore/bookstoreapi/data/configuration/DataInitializer.java
  src/main/java/com/bookstore/bookstoreapi/data/controller/BookController.java
  src/main/java/com/bookstore/bookstoreapi/data/entity/Book.java
  src/main/java/com/bookstore/bookstoreapi/data/service/BookService.java
Labels: 8 hours

#48 BSAPI-12-retrieve-book-details-by-isbn
  settings.gradle.kts
  src/main/java/com/bookstore/bookstoreapi/data/configuration/DataInitializer.java
  src/main/java/com/bookstore/bookstoreapi/data/controller/BookController.java
  src/main/java/com/bookstore/bookstoreapi/data/entity/Book.java
  src/main/java/com/bookstore/bookstoreapi/data/service/BookService.java
Labels: 4 hours

#49 BSAPI-12-retrieve-book-details-given-isbn
  src/main/java/com/bookstore/bookstoreapi/data/controller/BookController.java
  src/main/java/com/bookstore/bookstoreapi/data/repository/BookRepository.java
  src/main/java/com/bookstore/bookstoreapi/data/service/BookService.java
Labels: 2 hours

#52 BSAPI-28: Retrieve list of all comments for book
  src/main/java/com/bookstore/bookstoreapi/data/controller/BookController.java
  src/main/java/com/bookstore/bookstoreapi/data/entity/Book.java
  src/main/java/com/bookstore/bookstoreapi/data/service/BookService.java
Labels: 1 hour, Feature
